version: '3.5'

networks:
  authapp:
      name: 'authapp'
      driver: bridge
      
services:
  db:
    image: mysql:5.7
    container_name: db
    volumes:
      - /home/kshitij/data/mysql:/var/lib/mysql
    networks:
      - authapp
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306

  backend:
    container_name: backend
    image: authapp-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    expose: 
      - 8080
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: '3306'
    depends_on:
      - db    ports:
      - 8080:8080
    expose: 
      - 8080
    networks:
      - authapp